---
title: "Multiple Linear Regression Runs"
author: "Uyen Nguyen"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# Loading in tidyverse and dataset
library(tidyverse)
library(GGally)
library(MASS)

# Raw diabetes set
diabetes <- as_tibble(read.csv('diabetes2.csv'))


# Change Outcome variable to factor with appropriate labels
diabetes$Outcome <- factor(diabetes$Outcome)
levels(diabetes$Outcome)
levels(diabetes$Outcome) <- c("No","Yes")
levels(diabetes$Outcome)

# Diabetes set without Insulin, Skin Thickness and complete cases only 
diabetes2 <- diabetes

zero_unknown_cols <-c("Glucose", "BloodPressure", "SkinThickness",
                      "Insulin", "BMI", "DiabetesPedigreeFunction",
                      "Age")

diabetes2[,zero_unknown_cols] <- replace(diabetes2[,zero_unknown_cols], diabetes2[,zero_unknown_cols]==0,NA)

diabetes2 <- dplyr::select(diabetes2, -c('SkinThickness', 'Insulin'))
diabetes2 <- diabetes2[complete.cases(diabetes2),]
```


# Last iteration of MLR

## Scatterplots
```{r}
GGally::ggpairs(diabetes2)
```

## Full MLR with Pregnancies, Blood Pressure, BMI, DiabetesPedigeeFunction, and Age
```{r}
result <- lm(Glucose ~ Pregnancies + BloodPressure + BMI + DiabetesPedigreeFunction + Age, data = diabetes2)
summary(result)
```

```{r}
yhat <- result$fitted.values
res <- result$residuals
diabetes2 <- data.frame(diabetes2, yhat, res)

ggplot(diabetes2, aes(x = yhat,y = res))+
  geom_point()+
  geom_hline(yintercept=0, color="red")+
  labs(x="Fitted y",
       y="Residuals",
       title="Residual Plot from full MLR")
```


```{r}
boxcox(result)
```


```{r}
acf(result$residuals)
```


```{r}
qqnorm(result$residuals)
qqline(result$residuals, col = "red")
```


```{r}
ystar <- log(diabetes2$Glucose)
diabetes2 <- data.frame(diabetes2, ystar)
```


```{r}
resultLog <- lm(ystar ~ BloodPressure + BMI + DiabetesPedigreeFunction + Age, data = diabetes2)
summary(resultLog)
```


```{r}
yhatLog <- resultLog$fitted.values
resLog <- resultLog$residuals
diabetes2 <- data.frame(diabetes2, yhatLog, resLog)

ggplot(diabetes2, aes(x = yhatLog,y = resLog))+
  geom_point()+
  geom_hline(yintercept=0, color="red")+
  labs(x="Fitted log y",
       y="Residuals",
       title="Residual Plot from Reduced 3 log")
```


```{r}
boxcox(resultLog)
```


```{r}
acf(resultLog$residuals)
```



```{r}
qqnorm(resultLog$residuals)
qqline(resultLog$residuals, col = "red")
```















